app = "funbunn"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
  release_command = "/app/bin/migrate"

[build]
  dockerfile = "Dockerfile"

[env]
  FLY_DEPLOY = "true"
  ECTO_IPV6 = "true"
  STORE = "postgres"

[experimental]
  allowed_public_ports = []
  auto_rollback = true