app = "funbunn"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "Dockerfile"

[env]
  FLY_DEPLOY = "true"
  ECTO_IPV6 = "true"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
